before_script:
  - apt -qq update
  - apt -qq install -y hugo
  - hugo version
  - apt -qq install -y golang-go
  - go version

pages:
  stage: deploy
  script:
  - hugo
  artifacts:
    paths:
    - public/
  only:
  - master
