image: debian:bookworm-20250520-slim

before_script:
  - apt-get -qq update

  # Install mise & its tools
  - curl https://mise.run | sh
  - mise install
pages:
  stage: deploy
  script:
  - mise ci
  artifacts:
    paths:
    - public/
  only:
  - master
