image: python:latest

variables:
  PELICAN_THEMES_PATH: "$CI_PROJECT_DIR/themes"
  PELICAN_PLUGINS_PATH: "$CI_PROJECT_DIR/plugins"

  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"
  PIPENV_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  PIPENV_VENV_IN_PROJECT: "true"

cache:
  paths:
    - themes/
    - plugins/

    - .pip_cache/
    - .cache/
    - .venv/

before_script:
  - ./clone_or_pull_pelican_dirs.sh

  - apt update
  - apt install -y emacs25

  - python -V  # Print out python version for debugging
  - pip install pipenv
  - pipenv install --ignore-pipfile

pages:
  stage: deploy
  script:
  - pipenv run make publish
  artifacts:
    paths:
    - public/
  only:
  - master
