image: golang:latest

before_script:
  - apt-get -qq update
  - apt-get -qq install -y hugo
  - hugo version
  - go version

pages:
  stage: deploy
  script:
  - hugo
  artifacts:
    paths:
    - public/
  only:
  - master
