image: python:latest

variables:
  PELICAN_THEMES_PATH: "$CI_PROJECT_DIR/themes"
  PELICAN_PLUGINS_PATH: "$CI_PROJECT_DIR/plugins"

  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  PIPENV_VENV_IN_PROJECT: "true"

cache:
  paths:
    - themes/
    - plugins/

    - .cache/
    - .venv/

before_script:
  - apt -qq update
  - apt -qq install -y emacs25

  - python -V  # Print out python version for debugging
  - pip install pipenv
  - pipenv install --ignore-pipfile
  - pipenv run ./clone_or_pull_pelican_dirs.py

pages:
  stage: deploy
  script:
  - pipenv run make publish
  artifacts:
    paths:
    - public/
  only:
  - master

after_script:
  - mkdir -p .cache
